### ISSUE TITLE
English README from another lang

### ISSUE THREAD

**Issue by ProtossDragoon** [Lin-jun-xiang/action-translate-readme#10]
Hi, and thank you for developing this project.

I've encountered an issue where the target languages 'en,zh-CN' (or en, zh-CN separately) are not functioning correctly. My main README.md is written in Korean, and I wish to translate it into both English and Chinese. While the translation to Chinese works well, the English version of the README is not being generated. Could you assist with this problem?

Thanks

```yaml
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Auto Translate (en)
        uses: Lin-jun-xiang/action-translate-readme@v2
        with:
          token: ${{ secrets.PAT_PROTOSSDRAGOON_FOR_ACTIONBOT }}
          g4f_provider: g4f.Provider.DeepAi # You can change this provider
          langs: "en,zh-CN"
```

```yaml
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Auto Translate (en)
        uses: Lin-jun-xiang/action-translate-readme@v2
        with:
          token: ${{ secrets.PAT_PROTOSSDRAGOON_FOR_ACTIONBOT }}
          g4f_provider: g4f.Provider.DeepAi # You can change this provider
          langs: "en"

      - name: Auto Translate (zh-CN)
        uses: Lin-jun-xiang/action-translate-readme@v2
        with:
          token: ${{ secrets.PAT_PROTOSSDRAGOON_FOR_ACTIONBOT }}
          g4f_provider: g4f.Provider.DeepAi # You can change this provider
          langs: "zh-CN"
```
